### PR TITLE
Added package ranger_utils

### PR DESCRIPTION
**Pull request by guilherme-santos**
- added method to export envvars based on a file

### CODE REVIEW

**Comment by guilherme-santos** [comment]
Not sure about create a new package, but I didn't feel that it's a good fit on the packages that we already have!

**Comment by guilherme-santos** [comment]
@fabioesposito go-ranger is a util library, I didn't really like to create a package inside of it called `ranger_utils` but i couldn't think in anything better.. Do you have an idea what name I can use or even if it's make sense put inside a existing package?

**Comment by williancarminato** [comment]
@guilherme-santos I would say either `ranger_os` or `ranger_config`. In my personal opinion `ranger_os` is better as is the same that the language use. E.g https://gobyexample.com/environment-variables

**Comment by fabioesposito** [comment]
@guilherme-santos ranger_os looks good and aligned with main go libraries

**Pull request merged**
